version: '3.7'
services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.12.1
    container_name: filebeat
    hostname: filebeat.cn
    user: root
    environment:
      ELASTICSEARCH_HOST: es:9200
      KIBANA_HOST: kibana:5601
    command: ["--strict.perms=false"]
    networks: 
      - elastic
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./logs:/usr/share/filebeat/logs
      - /var/lib/docker/containers:/var/lib/docker/containers
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  elastic:
    external:
      name: elastic