filebeat.inputs:
  - type: container
    paths:
      - /var/lib/docker/containers/*/*.log
      
filebeat.autodiscover:
  providers:
    - type: docker
      templates:
        - condition:
            contains:
              docker.container.image: "log"
          config:
            - type: container
              paths:
                - /var/lib/docker/containers/${data.docker.container.id}/*.log

setup.ilm.enabled: false
setup.kibana:
  host: kibana:5601

setup.template.name: "filebeat"
setup.template.pattern: "filebeat-*"

output.elasticsearch:
  hosts: ["es:9200"]
  index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"
