version: '3.7'
# 首次使用需创建basic网络:$ docker network create basic -d bridge
networks: 
    default: 
        external: 
            name: basic
services: 
    nginx: 
        container_name: nginx
        image: nginx:latest
        ports: 
            - 80:80
        volumes: 
        - /var/run/docker.sock:/var/run/docker.sock
        - ./ubuntu.sources.list:/etc/apt/sources.list
        - ./nginx/conf.d:/etc/nginx/conf.d
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    mysql-5.7:
        container_name: mysql
        image: mysql:5.7.30
        restart: always
        ports: 
            - 3306:3306
        expose:
            - 3306
        networks:
            - default
        environment:
          - MYSQL_ROOT_PASSWORD=123456
    mongo:
        container_name: mongo
        image: mongo:latest
        restart: always
        ports: 
            - 27017:27017
        expose: 
            - 27017
        networks:
            - default
        command: mongod --config /etc/mongo/mongod.conf
        volumes: 
            - /var/run/docker.sock:/var/run/docker.sock
            - ./mongo/db:/data/db
            - ./mongo:/etc/mongo
            - ./mongo/logs/:/var/log/mongodb/
    redis:
        container_name: redis
        image: redis:latest
        restart: always
        ports: 
            - 6379:6379
        expose:
            - 6379
        networks:
            - default
        entrypoint: redis-server /etc/redis/redis.conf
        volumes: 
            - /var/run/docker.sock:/var/run/docker.sock
            - ./redis/redis.conf:/etc/redis/redis.conf
            - ./redis/data:/data
# docker容器管理器
    portainer:
        container_name: portainer
        image: portainer/portainer
        ports:
            - 9000:9000
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - default