version: '3.7'
networks: 
    default: 
        external: 
            name: basic
services: 
    mysql-5.7:
        container_name: mysql
        image: mysql:5.7.30
        restart: always
        ports: 
          - 3306:3306
        expose:
          - 3306
        networks:
        - default
        environment:
          - MYSQL_ROOT_PASSWORD=123456
    mongo:
        container_name: mongo-latest
        image: mongo:latest
        restart: always
        ports: 
            - 27017:27017
        expose: 
            - 27017
        networks:
            - default
        entrypoint: mongod
        volumes: 
            - /var/run/docker.sock:/var/run/docker.sock
            - /Users/17zuoye/docker/mongo/db:/data/db
    redis:
        container_name: redis-latest
        image: redis:latest
        restart: always
        ports: 
            - 6379:6379
        expose:
            - 6379
        networks:
            - default
        entrypoint: redis-server
        volumes: 
            - /var/run/docker.sock:/var/run/docker.sock
            - /Users/17zuoye/docker/redis/redis.conf:/etc/redis/redis.conf
            - /Users/17zuoye/docker/redis/data:/data